### PR TITLE
Error getting additional info using studentInfo()

### PR DESCRIPTION
**Pull request by thereal-cc**
With the following code in 'lib/StudentVue/Client/Client.js' starting at line 624:
```javascript
id: definedBox['@_GroupBoxID'][0],
type: definedBox['@_GroupBoxLabel'][0],
vcId: definedBox['@_VCID'][0],
```

I keep on getting the following error:
```bash
id: definedBox['@_GroupBoxID'][0],
                               ^
TypeError: Cannot read properties of undefined (reading '0')
```
I think this is because the client is trying to access the 0 index of an array-like variable, but the variable is undefined.
I found that what worked for me was removing the '[0]' from the end of the id and vcId, however I believe that this could also be a county specific issue.

Here's what works for me and my county: 
```javascript
id: definedBox['@_GroupBoxID'],
type: definedBox['@_GroupBoxLabel'][0],
vcId: definedBox['@_VCID'],
```
Hopefully that's all that's needed to fix everything, but if it isn't I can always look into other solutions as well.

### CODE REVIEW

**Comment by listingclown3** [comment]
For me, this same error happened with .studentInfo() 

Do you think this would work with .studentInfo() as well? I will try with other functions as well.

**Comment by thereal-cc** [comment]
This was a part of the code within .studentInfo(). It worked for me so hopefully it works for you as well.

**Comment by listingclown3** [comment]
> This was a part of the code within .studentInfo(). It worked for me so hopefully it works for you as well.

Yes, it worked. I see you have been making a StudentVUE Discord Bot. Add me on discord, let's chat! (list3#8004)

**Comment by vaporrrr** [comment]
You should be editing the .ts file not the .js file. The .js file is just the compiled .ts file.

**Comment by EGGaming** [comment]
@thereal-cc Like @vaporrrr explained, edit the `.ts` file instead.

the xml parsing library will convert everything to an array, so I suggest you use the `this.optional(xmlArr)` method. If not, the values will end up looking something like this:

```ts
id: string[] | undefined,
type: string,
vcId: string[] | undefined,
```

`this.optional(xmlArr)` is a lazy method I created which is a simple version of the single line if-else statement:
```js
xmlArr != null ? xmlArr[0] : undefined
```

In your case:
```ts
id: this.optional(definedBox['@_GroupBoxID']), // string | undefined
type: definedBox['@_GroupBoxLabel'][0], // string
vcId: this.optional(definedBox['@_VCID']), // string | undefined
```

Since the fields `id` and `vcId` were undefined for you, this is probably a county-specific thing because in my district they are defined last time I checked.

**Comment by listingclown3** [comment]
It is county specific. Maybe add a disclaimer (?) that tells people that some functions won't work because some counties don't put all of a students info into StudentVUE (like me). Just a suggestion of course.

**Comment by EGGaming** [comment]
> It is county specific. Maybe add a disclaimer (?) that tells people that some functions won't work because some counties don't put all of a students info into StudentVUE (like me). Just a suggestion of course.

Sounds like a good idea, will do.

**Pull request merged**
